/// Represents the role of a message in a conversation.
///
/// Follows the OpenAI chat completion API convention for message roles.
enum ChatMessageRole {
  /// System message that provides instructions to the model.
  ///
  /// Typically used as the first message in a conversation to set the
  /// model's behavior and personality.
  system('system'),

  /// User message representing human input.
  ///
  /// Contains the questions, requests, or content from the end user.
  user('user'),

  /// Assistant message representing model-generated output.
  ///
  /// Contains responses generated by the AI model.
  assistant('assistant'),

  /// Tool message containing function call results.
  ///
  /// Used to provide the results of function calls back to the model
  /// so it can continue the conversation with that context.
  tool('tool');

  /// Creates a new [ChatMessageRole] with the given string [value].
  const ChatMessageRole(this.value);

  /// The string representation of this role.
  ///
  /// Used for JSON serialization and API communication.
  final String value;

  /// Creates a [ChatMessageRole] from its string representation.
  ///
  /// Throws [ArgumentError] if the string doesn't match any known role.
  factory ChatMessageRole.fromString(String value) {
    return ChatMessageRole.values.firstWhere(
      (role) => role.value == value,
      orElse: () => throw ArgumentError('Unknown role: $value'),
    );
  }

  @override
  String toString() => value;
}
