import 'chat_message.dart';
import 'generation_stats.dart';
import '../function_calling/leap_function_call.dart';

/// Represents a response from the model during generation.
///
/// The model streams responses as a sequence of [MessageResponse] values.
/// Use pattern matching to handle different response types.
///
/// ## Example
///
/// ```dart
/// await for (final response in conversation.generateResponse(message: msg)) {
///   switch (response) {
///     case ChunkResponse(:final text):
///       print(text); // Print streamed text
///     case ReasoningChunkResponse(:final reasoning):
///       print('Thinking: $reasoning');
///     case AudioSampleResponse(:final samples, :final sampleRate):
///       audioPlayer.enqueue(samples, sampleRate);
///     case FunctionCallResponse(:final calls):
///       for (final call in calls) {
///         await handleFunctionCall(call);
///       }
///     case CompleteResponse(:final message, :final stats):
///       print('Done! ${stats?.totalTokens} tokens');
///   }
/// }
/// ```
sealed class MessageResponse {
  /// Creates a new [MessageResponse].
  const MessageResponse();
}

/// A chunk of generated text.
///
/// Emitted during streaming as the model generates tokens.
class ChunkResponse extends MessageResponse {
  /// Creates a new [ChunkResponse].
  const ChunkResponse(this.text);

  /// The text content of this chunk.
  final String text;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ChunkResponse && other.text == text;
  }

  @override
  int get hashCode => text.hashCode;

  @override
  String toString() => 'ChunkResponse($text)';
}

/// A chunk of reasoning text from a reasoning model.
///
/// Emitted by models that expose their reasoning process.
/// The reasoning content is typically wrapped in `<think>` tags.
class ReasoningChunkResponse extends MessageResponse {
  /// Creates a new [ReasoningChunkResponse].
  const ReasoningChunkResponse(this.reasoning);

  /// The reasoning text content.
  final String reasoning;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ReasoningChunkResponse && other.reasoning == reasoning;
  }

  @override
  int get hashCode => reasoning.hashCode;

  @override
  String toString() => 'ReasoningChunkResponse($reasoning)';
}

/// Audio samples generated by the model.
///
/// Emitted by audio-capable models. Samples are 32-bit float PCM data.
class AudioSampleResponse extends MessageResponse {
  /// Creates a new [AudioSampleResponse].
  const AudioSampleResponse({
    required this.samples,
    required this.sampleRate,
  });

  /// The audio samples as 32-bit floats.
  final List<double> samples;

  /// The sample rate in Hz (e.g., 16000 for 16kHz).
  final int sampleRate;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! AudioSampleResponse) return false;
    if (sampleRate != other.sampleRate) return false;
    if (samples.length != other.samples.length) return false;
    for (var i = 0; i < samples.length; i++) {
      if (samples[i] != other.samples[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(Object.hashAll(samples), sampleRate);

  @override
  String toString() =>
      'AudioSampleResponse(${samples.length} samples at ${sampleRate}Hz)';
}

/// Function call requests from the model.
///
/// Emitted when the model determines it needs to call registered functions.
/// The app should execute the functions and provide results back to the model.
class FunctionCallResponse extends MessageResponse {
  /// Creates a new [FunctionCallResponse].
  const FunctionCallResponse(this.calls);

  /// The list of function calls requested by the model.
  final List<LeapFunctionCall> calls;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! FunctionCallResponse) return false;
    if (calls.length != other.calls.length) return false;
    for (var i = 0; i < calls.length; i++) {
      if (calls[i] != other.calls[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hashAll(calls);

  @override
  String toString() => 'FunctionCallResponse(${calls.length} calls)';
}

/// Signals the completion of generation.
///
/// Contains the full generated message and optional statistics.
class CompleteResponse extends MessageResponse {
  /// Creates a new [CompleteResponse].
  const CompleteResponse({
    required this.message,
    required this.finishReason,
    this.stats,
  });

  /// The complete generated message.
  final ChatMessage message;

  /// The reason generation finished.
  final GenerationFinishReason finishReason;

  /// Optional generation statistics.
  ///
  /// May be null if statistics are not available.
  final GenerationStats? stats;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! CompleteResponse) return false;
    return message == other.message &&
        finishReason == other.finishReason &&
        stats == other.stats;
  }

  @override
  int get hashCode => Object.hash(message, finishReason, stats);

  @override
  String toString() =>
      'CompleteResponse(finishReason: $finishReason, stats: $stats)';
}
